version: "3"
services:
    # start the ganache cli container
    ganache-cli:
        container_name: pi_ganache-cli
        build:
            context: docker/pi-ganache-cli
        # note host:container
        ports:
            - 5545:8545
    truffle_suite:
        container_name: pi_truffle_suite
        build:
            context: docker/pi-truffle-suite
                # volumes
        volumes:
            - ".:/workspace"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
